# Generated by Django 4.0.1 on 2022-01-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='users/images/', verbose_name='عکس کاربر'),
        ),
    ]
