# Generated by Django 4.0.1 on 2022-02-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0007_alter_customuser_managers_customuser_about_me_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='about_me',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='درباره من'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='موقعیت فعلی'),
        ),
    ]
