# Generated by Django 4.0.1 on 2022-02-03 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='26 * 103', null=True, upload_to='logos/', verbose_name='لوگوی سایت')),
                ('name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='نام سایت')),
                ('copy_right', models.CharField(blank=True, max_length=200000, null=True, verbose_name='نوشته قانون کی رایت')),
            ],
            options={
                'verbose_name': 'تنظیم سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10000, null=True, verbose_name='نام شبکه')),
                ('url', models.URLField(blank=True, null=True, verbose_name='آدرس اینترنتی')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_settings_app.setting')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='شماره تلفن')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_settings_app.setting')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_settings_app.setting')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_settings_app.setting')),
            ],
        ),
    ]
