# Generated by Django 4.0.1 on 2022-02-03 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس  های شرکت'},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'ایمیل سایت', 'verbose_name_plural': 'ایمیل های سایت'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'شماره تلفن', 'verbose_name_plural': 'تلفن های سایت'},
        ),
        migrations.AlterModelOptions(
            name='socialnetwork',
            options={'verbose_name': 'شبکه سایت', 'verbose_name_plural': 'شبکه های سایت'},
        ),
    ]
