# Generated by Django 4.0.1 on 2022-02-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings_app', '0002_alter_address_options_alter_email_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoHomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100000, null=True, verbose_name='title')),
                ('keywords', models.CharField(blank=True, max_length=10000, null=True, verbose_name='keywords')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'سئو',
                'verbose_name_plural': 'سثو صفحه ی اصلی',
            },
        ),
    ]
