# Generated by Django 4.0.1 on 2022-02-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings_app', '0003_seohomepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='fave_icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
