# Generated by Django 4.0.1 on 2022-02-05 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings_app', '0004_setting_fave_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='fave_icon',
            new_name='fav_icon',
        ),
    ]
