# Generated by Django 4.0.1 on 2022-02-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings_app', '0006_alter_setting_fav_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='fav_icon',
            field=models.ImageField(blank=True, help_text='80 * 80', null=True, upload_to='icons/', verbose_name='فاو آیکون'),
        ),
    ]
