# Generated by Django 4.0.1 on 2022-02-03 15:49

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='عنوان')),
                ('content', tinymce.models.HTMLField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='تام و نام خانوادگی')),
                ('job', models.CharField(max_length=1000, verbose_name='شغل')),
                ('image', models.ImageField(upload_to='images/teams/', verbose_name='تصویر')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutUs_app.aboutus', verbose_name='درباره ما')),
            ],
            options={
                'verbose_name': 'عضو',
                'verbose_name_plural': 'اعضا',
            },
        ),
    ]
