# Generated by Django 4.0.1 on 2022-02-03 20:42

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='team',
            name='about_us',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aboutUs_app.aboutus', verbose_name='درباره ما'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/teams/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='team',
            name='job',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='شغل'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='تام و نام خانوادگی'),
        ),
    ]
