# Generated by Django 4.0.1 on 2022-02-03 16:37

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=1000, verbose_name='عنوان تماس')),
                ('message', models.TextField(verbose_name='پیغام')),
                ('date_send', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ ارسال')),
            ],
            options={
                'verbose_name': 'تماس کاربر',
                'verbose_name_plural': 'تماس های کاربران',
            },
        ),
    ]
