# Generated by Django 4.0.1 on 2022-01-31 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='دسته بندی')),
                ('slug', models.SlugField(help_text='برای مثال: category-name', max_length=1000, verbose_name='نام انگلیسی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='دسته بندی')),
                ('slug', models.SlugField(help_text='برای مثال: category-name', max_length=1000, verbose_name='نام انگلیسی')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب ها',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000, verbose_name='عنوان پست')),
                ('content', tinymce.models.HTMLField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='blog/images/', verbose_name='تصویر پست')),
                ('date_created', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ ایجاد')),
                ('date_update', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ بروزرسانی')),
                ('status', models.CharField(choices=[('u', 'منتشر نشود'), ('w', 'درحال بررسی'), ('p', 'منتشر شود')], default='u', max_length=1000)),
                ('visit_count', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.category', verbose_name='انتخاب دسته بندی')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('tag', models.ManyToManyField(to='blog_app.Tag', verbose_name='انتخاب برچسب')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
            },
        ),
    ]
