# Generated by Django 4.0.1 on 2022-01-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('u', 'منتشر نشود'), ('w', 'درحال بررسی'), ('p', 'منتشر شود')], default='u', max_length=1000, verbose_name='وضعیت'),
        ),
    ]
