# Generated by Django 4.0.1 on 2022-01-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_article_visit_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='برای مثال: tag-name', max_length=1000, verbose_name='نام انگلیسی'),
        ),
    ]
