# Generated by Django 4.0.1 on 2022-01-31 13:36

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_update',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
