# Generated by Django 4.0.1 on 2022-01-31 13:37

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_alter_article_date_created_alter_article_date_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=django_jalali.db.models.jDateTimeField(verbose_name='تاریخ ایجاد'),
        ),
    ]
