# Generated by Django 4.0.1 on 2022-01-31 17:13

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_alter_article_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_update',
            field=django_jalali.db.models.jDateTimeField(verbose_name='تاریخ بروزرسانی'),
        ),
    ]
