# Generated by Django 4.0.1 on 2022-02-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_alter_article_date_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video_url',
            field=models.URLField(default='', verbose_name='لینک ویدئو'),
        ),
    ]
