# Generated by Django 4.0.1 on 2022-02-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_article_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='video_url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='لینک ویدئو'),
        ),
    ]
