# Generated by Django 4.0.1 on 2022-02-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_articlegallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlegallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article/gallery/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='articlegallery',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='عنوان'),
        ),
    ]
