# Generated by Django 4.0.1 on 2022-02-02 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0012_alter_articlegallery_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlegallery',
            options={'verbose_name': 'تصویر', 'verbose_name_plural': 'گالری'},
        ),
    ]
