# Generated by Django 4.0.1 on 2022-02-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0013_alter_articlegallery_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(help_text='750 * 440', upload_to='blog/images/', verbose_name='تصویر پست'),
        ),
        migrations.AlterField(
            model_name='articlegallery',
            name='image',
            field=models.ImageField(blank=True, help_text='466 * 353', null=True, upload_to='article/gallery/', verbose_name='تصویر'),
        ),
    ]
