# Generated by Django 4.0.1 on 2022-02-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0014_alter_article_image_alter_articlegallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(help_text='440 * 750', upload_to='blog/images/', verbose_name='تصویر پست'),
        ),
        migrations.AlterField(
            model_name='articlegallery',
            name='image',
            field=models.ImageField(blank=True, help_text='353 * 466', null=True, upload_to='article/gallery/', verbose_name='تصویر'),
        ),
    ]
