# Generated by Django 4.0.1 on 2022-02-03 00:11

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0016_articlecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='date_send',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2022, 2, 3, 0, 11, 1, 157711), verbose_name='تاریخ ارسال'),
            preserve_default=False,
        ),
    ]
