# Generated by Django 4.0.1 on 2022-02-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0017_articlecomment_date_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecomment',
            name='is_accept',
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='status',
            field=models.CharField(choices=[('a', 'قبول شود'), ('r', 'رد شود')], default='r', max_length=1000, verbose_name='وضعیت'),
        ),
    ]
