# Generated by Django 4.0.1 on 2022-02-03 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0019_alter_article_visit_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_app.category', verbose_name='انتخاب دسته بندی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='article',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_update',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text='440 * 750', null=True, upload_to='blog/images/', verbose_name='تصویر پست'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(blank=True, choices=[('u', 'منتشر نشود'), ('w', 'درحال بررسی'), ('p', 'منتشر شود')], default='u', max_length=1000, null=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='blog_app.Tag', verbose_name='انتخاب برچسب'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='عنوان پست'),
        ),
        migrations.AlterField(
            model_name='article',
            name='visit_count',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='تعداد بازدید'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_app.article', verbose_name='پست'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='date_send',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='name',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'قبول شود'), ('r', 'رد شود')], default='r', max_length=1000, null=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='پیغام'),
        ),
        migrations.AlterField(
            model_name='articlegallery',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_app.article', verbose_name='پست'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='برای مثال: category-name', max_length=1000, null=True, verbose_name='نام انگلیسی'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, help_text='برای مثال: tag-name', max_length=1000, null=True, verbose_name='نام انگلیسی'),
        ),
    ]
