# Generated by Django 4.0.1 on 2022-02-03 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0020_alter_article_category_alter_article_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoArticleList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100000, null=True, verbose_name='name')),
                ('keywords', models.CharField(blank=True, max_length=10000, null=True, verbose_name='کلمات ویژه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='کلمات ویژه')),
            ],
            options={
                'verbose_name': 'سئو',
                'verbose_name_plural': 'سثو صفحه ی لیست پست ها',
            },
        ),
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100000, null=True, verbose_name='name')),
                ('keywords', models.CharField(blank=True, max_length=10000, null=True, verbose_name='کلمات ویژه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='کلمات ویژه')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_app.article')),
            ],
            options={
                'verbose_name': 'سئو',
                'verbose_name_plural': 'سثو پست ها',
            },
        ),
    ]
