# Generated by Django 4.0.1 on 2022-02-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0021_seoarticlelist_seo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='keywords',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='title',
            field=models.CharField(blank=True, max_length=100000, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='seoarticlelist',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='seoarticlelist',
            name='keywords',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='seoarticlelist',
            name='title',
            field=models.CharField(blank=True, max_length=100000, null=True, verbose_name='title'),
        ),
    ]
