# Generated by Django 4.0.1 on 2022-02-03 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0022_alter_seo_description_alter_seo_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_app.article', verbose_name='پست'),
        ),
    ]
