# Generated by Django 4.0.1 on 2022-02-03 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0023_alter_seo_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.article', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'پست پیشنهادی',
                'verbose_name_plural': 'پست های پیشنهادی مدیر',
            },
        ),
    ]
