# Generated by Django 4.0.1 on 2022-02-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0026_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, to='blog_app.Tag', verbose_name='انتخاب برچسب'),
        ),
    ]
