# Generated by Django 4.0.1 on 2022-02-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0027_alter_article_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='keywords',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='seoarticlelist',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='title'),
        ),
    ]
