# Generated by Django 4.0.1 on 2022-02-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0028_alter_seo_keywords_alter_seo_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='عنوان پست'),
        ),
    ]
