# Generated by Django 4.0.1 on 2022-03-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0029_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(blank=True, choices=[('n', ''), ('u', 'منتشر نشود'), ('w', 'درحال بررسی'), ('p', 'منتشر شود')], default='u', max_length=1000, null=True, verbose_name='وضعیت'),
        ),
    ]
