# Generated by Django 4.0.1 on 2022-03-05 17:13

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0032_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog_app.category', verbose_name='انتخاب دسته بندی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=django_jalali.db.models.jDateTimeField(auto_created=True, blank=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_update',
            field=django_jalali.db.models.jDateTimeField(auto_created=True, blank=True, null=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
