# Generated by Django 4.0.1 on 2022-02-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='status',
            field=models.CharField(choices=[('u', 'منتشر نشود'), ('p', 'منتشر شود')], default='u', max_length=100),
        ),
    ]
