# Generated by Django 4.0.1 on 2022-02-04 16:30

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('slider_app', '0003_alter_slider_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='عنوان'),
        ),
    ]
