# Generated by Django 4.0.1 on 2022-02-04 16:39

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='date_send',
            field=django_jalali.db.models.jDateTimeField(verbose_name='تاریخ عضویت'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
    ]
